language: php

php:
- php: 5.5
- php: 5.6
- php: 5.6
  env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
- php: 7.0
- php: hhvm
- php: nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./ --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
